version: '3.3'
services:

  postgres_backend_api:
    image: postgres:latest
    container_name: LablesTest
    env_file: .env
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin_
    depends_on:
      - postgres_backend_api
    ports:
      - 82:80
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mail.ru
      PGADMIN_DEFAULT_PASSWORD: test
    logging:
      driver: none
